image:
  repository: sealife/fritzbox-exporter
  tag: 1.0
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

deployment:
  enabled: true
  kind: Deployment
  replicas: 1
  annotations: {}
  labels: {}

service:
  enable: true
  type: ClusterIP
  annotations: {}
  labels: {}

env:
  - name: TZ
    value: UTC

ports:
  metrics:
    enabled: true
    port: 8765
    protocol: TCP

serviceAccount:
  name: ''

resources: {}
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
