{{- if .Values.service.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "fritzbox-exporter.fullname" . }}
  labels:
    {{- include "fritzbox-exporter.labels" . | nindent 4 }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
  {{- with .Values.deployment.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- range $key, $val := .Values.ports }}
    {{- if $val.enabled }}
    - name: {{ $key | quote }}
      port: {{ $val.port }}
      targetPort: {{ $key | quote }}
      protocol: {{ $val.protocol | default "TCP" }}
    {{- end }}
    {{- end }}
  selector:
    {{- include "fritzbox-exporter.selectorLabels" . | nindent 4 }}
{{- end }}
