# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: paperless
description: A Helm chart for paperless-ngx
version: 5.0.0
# renovate: image=ghcr.io/paperless-ngx/paperless-ngx
appVersion: "2.2.1"

home: https://charts.pascaliske.dev/charts/paperless/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/paperless-ngx/paperless-ngx
keywords:
  - paperless
  - paperless-ngx
  - document-management-system
  - dms
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev
  - name: redis
    version: 1.1.3
    repository: https://charts.pascaliske.dev
    condition: redis.enabled

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove support for CRDs from "traefik.containo.us".'
    - kind: added
      description: 'Add support for CRDs from "traefik.io".'
