# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: plausible
description: A Helm chart for Plausible
version: 1.0.0
# renovate: image=plausible/analytics
appVersion: "v2.0.0"

home: https://charts.pascaliske.dev/charts/plausible/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/plausible/analytics
  - https://github.com/plausible/hosting
  - https://plausible.io
keywords:
  - plausible
  - analytics
  - privacy-focused
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |-
    - kind: removed
      description: 'Remove support for CRDs from "traefik.containo.us".'
    - kind: added
      description: 'Add support for CRDs from "traefik.io".'
    - kind: changed
      description: 'Switch to GHCR based image for GeoIP database.'
