# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: gitlab
description: A Helm chart for GitLab Omnibus
version: 2.0.5
# renovate: image=gitlab/gitlab-ce
appVersion: "16.1.2-ce.0"

home: https://charts.pascaliske.dev/charts/gitlab/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://docs.gitlab.com
keywords:
  - gitlab
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
