# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: uptime-kuma
description: A Helm chart for Uptime-Kuma
version: 1.0.6
# renovate: image=louislam/uptime-kuma
appVersion: "1.23.3"

home: https://charts.pascaliske.dev/charts/uptime-kuma/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/louislam/uptime-kuma
keywords:
  - uptime
  - uptime-kuma
  - monitoring
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: 'Updated Uptime-Kuma to v1.22.1.'
