# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: cloudflared
description: A Helm chart for cloudflared DNS over HTTPS tunnel.
version: 2.0.4
# renovate: image=ghcr.io/crazy-max/cloudflared
appVersion: "2023.5.1"

home: https://charts.pascaliske.dev/charts/cloudflared/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/crazy-max/docker-cloudflared
keywords:
  - cloudflared
  - dns-over-https
  - dns-proxy
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.1.1
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
