# yaml-language-server: $schema=https://json.schemastore.org/chart.json
apiVersion: v2
type: application
name: snapdrop
description: A Helm chart for snapdrop
version: 1.0.4
# renovate: image=ghcr.io/linuxserver/snapdrop
appVersion: "version-724f0af5"

home: https://charts.pascaliske.dev/charts/snapdrop/
sources:
  - https://github.com/pascaliske/helm-charts
  - https://github.com/linuxserver/docker-snapdrop
  - https://github.com/RobinLinus/snapdrop
keywords:
  - snapdrop
  - airdrop
maintainers:
  - name: pascaliske
    email: info@pascaliske.dev
    url: https://pascaliske.dev

dependencies:
  - name: base
    version: 1.2.0
    repository: https://charts.pascaliske.dev

annotations:
  artifacthub.io/changes: |
    - kind: removed
      description: 'Remove values schema due to issues with flux variable substitution.'
